services:
  rotoreader-postgres:
    image: pgvector/pgvector:pg18
    container_name: rotoreader-postgres
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-postgres}
      POSTGRES_DB: ${POSTGRES_DB:-rotoreader}
      POSTGRES_SSLMODE: ${POSTGRES_SSLMODE:-disable}
    # restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER:-postgres} -d ${POSTGRES_DB:-rotoreader}"]
      interval: 10s
    ports:
      - "${POSTGRES_PORT:-5432}:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      # - ./docker/data/postgres:/var/lib/postgresql/data
      # - ./src/schema/postgres.sql:/docker-entrypoint-initdb.d/schema.sql


  rotoreader-app:
    build: .
    container_name: rotoreader-app
    env_file:
      - .env
    environment:
      ROOT_DIR: /app
      POSTGRES_HOST: rotoreader-postgres
      POSTGRES_PORT: 5432
    ports:
      - "${APP_PORT:-8081}:${APP_PORT:-8081}"
    depends_on:
      rotoreader-postgres:
        condition: service_healthy


volumes:
  postgres_data:
    # driver: local