[project]
name = "news-reader"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12,<3.13"
dependencies = [
    "feedparser>=6.0.12",
]

[dependency-groups]
dev = [
    "ipykernel>=6.30.1",
]
