###
@BASE_URL = http://localhost:{{ $dotenv APP_PORT }}

# Health Check
GET {{BASE_URL}}/


###

# Trigger Feed Collection and Processing
PUT {{BASE_URL}}/collect?limit=1

###

# Test Prometheus Endpoint
GET {{BASE_URL}}/metrics

###

# Get all FeedDatas
GET {{BASE_URL}}/feed/

###

# Get all FeedDatas
GET {{BASE_URL}}/feed?size=1

###

# Get Team FeedDatas
GET {{BASE_URL}}/feed?team=BUF

